apiVersion: v1
kind: Service
metadata:
  name: k3s-admin
  namespace: k3s-admin
  labels:
    app: k3s-admin
spec:
  type: NodePort
  selector:
    app: k3s-admin
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 30080
